# Generated by Django 2.0.7 on 2018-08-03 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_auto_20180803_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='externalid',
            new_name='external_id',
        ),
    ]
