# Generated by Django 2.1.1 on 2018-09-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_auto_20180803_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecimenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('collectdate', models.DateTimeField()),
                ('collecttime', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='pid',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='specimenmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.PatientModel'),
        ),
    ]
