# Generated by Django 2.1.1 on 2018-09-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_auto_20180917_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimentype',
            name='type',
            field=models.CharField(choices=[('DBS', 'Dried Blood Spot')], default='DBS', max_length=30),
        ),
    ]
