# Generated by Django 2.1.1 on 2018-09-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_specimentype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimentype',
            name='type',
            field=models.CharField(choices=[('Dried Blood Spot', 'DBS')], max_length=30),
        ),
    ]
