# Generated by Django 2.1.1 on 2018-09-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0008_auto_20180917_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='lims.SpecimenType'),
        ),
    ]
