# Generated by Django 2.1.1 on 2018-09-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0010_auto_20180918_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specimenmodel',
            old_name='type_id',
            new_name='type',
        ),
    ]
