# Generated by Django 2.1.1 on 2018-10-31 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0012_specimenmodel_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='aliquotmodel',
            name='collectdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aliquotmodel',
            name='collecttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aliquotmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aliquotmodel',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aliquotmodel',
            name='specimen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lims.SpecimenModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aliquotmodel',
            name='type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='types', to='lims.AliquotType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aliquotmodel',
            name='volume',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aliquottype',
            name='type',
            field=models.CharField(default='Dried Blood Spot', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aliquottype',
            name='units',
            field=models.CharField(default='ml', max_length=10),
            preserve_default=False,
        ),
    ]
