# Generated by Django 2.1.1 on 2018-11-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0014_auto_20181101_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliquotmodel',
            name='collecttime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='specimenmodel',
            name='collecttime',
            field=models.TimeField(),
        ),
    ]
